updated ukrainian and russian
Voxelum/x-minecraft-launcher pull request #732
Opened 2024-08-19 11:28 UTC by herosh1sh

updated Russian and Ukrainian lang.

2024-08-20 09:13 UTC, BANSAFAn commented
Ошибки в Ru.yaml проверьте пожалуйста, там очень много слов украинских !


*Не принимайте, пусть исправлят *

2024-08-20 14:04 UTC, herosh1sh commented
> Ошибки в Ru.yaml проверьте пожалуйста, там очень много слов украинских !
> 
> *Не принимайте, пусть исправлят *
Вы имеете в виду в 188 строчке "Утилiта i Qol"?

2024-08-20 16:06 UTC, BANSAFAn commented
> > Ошибки в Ru.yaml проверьте пожалуйста, там очень много слов украинских !
> > *Не принимайте, пусть исправлят *
> > Вы имеете в виду в 188 строчке "Утилiта i Qol"?

Верно, на 188 строке "ru" там написанно` і Утіліта`

2024-08-20 16:06 UTC, BANSAFAn commented
Не ну я конечно могу потом исправить те ошибки в случии чего, но просто советую исправить это, остально ладно уже катит !

2024-08-21 10:26 UTC, BANSAFAn commented
Все, принимаю !

2024-08-21 13:22 UTC, herosh1sh commented
> Все, принимаю !

Получается в следующем обновлении всё будет?

2024-08-21 16:24 UTC, BANSAFAn commented
> > Все, принимаю !
> 
> Получается в следующем обновлении всё будет?

Честно я не знаю, щас пусть ветку соединит разраб

2024-08-21 16:41 UTC, BANSAFAn commented
Ты знаешь японский ?

Я лично частично знаю его )

2024-08-23 17:03 UTC, ci010 commented
Could you please don't include the file [.vscode/i18n-ally-reviews.yml](https://github.com/Voxelum/x-minecraft-launcher/pull/732/files#diff-c9e572d83190cbd7f720ea13b0c3d0b9e2c9b8e507fc6e1bd22571f1995af465) into the PR?

2024-08-26 05:42 UTC, ci010 requested changes

2024-08-26 05:42 UTC, ci010 commented on assets/locales.json
>    "hu": "Magyar"
```suggestion
  "hu": "Magyar",
  "ja": "日本語"
```

2024-08-26 05:42 UTC, ci010 commented on .vscode/settings.json
> +    "i18n-ally.sourceLanguage": "ru",
Done commit this file change

2024-09-05 09:40 UTC, herosh1sh reviewed
.

2024-10-22 17:28 UTC, closed without merging