new language Kazakhstan
Voxelum/x-minecraft-launcher pull request #834
Opened 2024-10-28 12:13 UTC by herosh1sh

230+ words has been trasnlated. I used to translate Google translate (sorry for error in words), and I fix minor errors in Russian, Ukrainian words

2024-10-28 17:08 UTC, BANSAFAn commented
> and added line "BANSAFAn who helps me a lot on the RU/UK community." In different language

UK - no ukraine, ua - it's ukraine

2024-10-28 17:10 UTC, BANSAFAn commented
There are errors in the lines, they are out of place and build is not possible

2024-10-29 05:00 UTC, herosh1sh commented
> > and added line "BANSAFAn who helps me a lot on the RU/UK community." In different language
> 
> UK - no ukraine, ua - it's ukraine

только в чем прикол, что если на UK readme перейдешь, то это будет украинский язык

2024-11-01 09:27 UTC, ci010 requested changes

2024-11-01 09:27 UTC, ci010 commented on .vscode/i18n-ally-reviews.yml
Can you don't commit this file?

2024-11-01 10:20 UTC, BANSAFAn commented on .vscode/i18n-ally-reviews.yml
> Can you don't commit this file?

Hike he throws and then leaves, I just see a lot of mistakes and do not want to correct, it is easier to rewrite in case of what, so I do not think that he sees your messages

2024-11-02 07:55 UTC, merged